"""initial schema

Revision ID: 93e39126d9d6
Revises:
Create Date: 2026-09-23 12:41:59.128125

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93e39126d9d6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("tg_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("time_zone", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("tg_id", name=op.f("pk_users")),
    )
    op.create_table(
        "persons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("fullname", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("birth_day", sa.Integer(), nullable=False),
        sa.Column("birth_month", sa.Integer(), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("birth_day BETWEEN 1 AND 31", name=op.f("ck_persons_birth_day_range")),
        sa.CheckConstraint(
            "birth_month BETWEEN 1 AND 12", name=op.f("ck_persons_birth_month_range")
        ),
        sa.ForeignKeyConstraint(
            ["tg_id"], ["users.tg_id"], name=op.f("fk_persons_tg_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_persons")),
    )
    op.create_index(op.f("ix_persons_tg_id"), "persons", ["tg_id"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("notify_days_before", sa.Integer(), nullable=False),
        sa.Column("notification_time", sa.Time(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tg_id"],
            ["users.tg_id"],
            name=op.f("fk_user_settings_tg_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_settings")),
    )
    op.create_index(op.f("ix_user_settings_tg_id"), "user_settings", ["tg_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_settings_tg_id"), table_name="user_settings")
    op.drop_table("user_settings")
    op.drop_index(op.f("ix_persons_tg_id"), table_name="persons")
    op.drop_table("persons")
    op.drop_table("users")
    # ### end Alembic commands ###
